In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Generate synthetic data (replace with your actual data)
# For demonstration purposes, we're using random data here
#np.random.seed(42)
#num_samples = 100
#sequence_length = 20
#data = np.random.rand(num_samples, sequence_length,4)  # Open, High, Low, Close

#print(data)


In [21]:

from sklearn.discriminant_analysis import StandardScaler


df = pd.read_csv('data/NASDAQ.csv')
#print(df.head())  # 7 columns, including the Date.

cols = list(df)[1:5]
# New dataframe with only training data - 5 columns
df_for_training = df[cols].astype(float)

df_for_training = df_for_training.tail(200)

In [22]:

# LSTM uses sigmoid and tanh that are sensitive to magnitude so values need to be normalized
# normalize the dataset
scaler = StandardScaler()
scaler = scaler.fit(df_for_training)
data = scaler.transform(df_for_training)
print(data)


[[-1.29857219e+00 -1.13038944e+00 -1.23794847e+00 -1.05963789e+00]
 [-1.04095593e+00 -1.03400772e+00 -1.08813195e+00 -9.77332749e-01]
 [-9.25970633e-01 -8.31176259e-01 -8.39484751e-01 -7.58914359e-01]
 [-9.50711788e-01 -8.35235420e-01 -8.82080095e-01 -9.61047373e-01]
 [-9.48117602e-01 -1.02040791e+00 -1.02924874e+00 -1.11904694e+00]
 [-1.13024486e+00 -9.14629612e-01 -1.04178439e+00 -8.44568121e-01]
 [-8.98122680e-01 -9.76410238e-01 -9.12209992e-01 -9.45842726e-01]
 [-7.86314207e-01 -8.79483684e-01 -9.40980427e-01 -1.03205546e+00]
 [-1.02507615e+00 -1.02531663e+00 -1.25506844e+00 -1.35639153e+00]
 [-1.45488725e+00 -1.47882160e+00 -1.43334036e+00 -1.51752686e+00]
 [-1.32326925e+00 -1.41836376e+00 -1.48296672e+00 -1.40029481e+00]
 [-1.35088640e+00 -1.38766990e+00 -1.33746316e+00 -1.32119812e+00]
 [-1.26715669e+00 -1.24669153e+00 -1.29904893e+00 -1.27540680e+00]
 [-1.34069811e+00 -1.40822502e+00 -1.41188944e+00 -1.50846308e+00]
 [-1.03909738e+00 -9.12769854e-01 -1.02973072e+00 -8.34201238e

In [23]:

num_samples = len(data)
sequence_length = 20


In [24]:
# Create synthetic zigzag labels
zigzag_indices = np.arange(0, num_samples, 5)
labels = np.zeros(num_samples)
labels[zigzag_indices] = 1

# Plot the data and zigzag patterns
fig, axs = plt.subplots(nrows=num_samples, sharex=True, figsize=(28, 12))
for i in range(num_samples):
    candle_data = data[i]
    ax = axs[i]

    # Plot candlestick
    candle_colors = ['g' if candle[3] >= candle[0]
                     else 'r' for candle in candle_data]
    ax.vlines(np.arange(sequence_length),
              candle_data[:, 1], candle_data[:, 2], color=candle_colors, linewidth=2)
    ax.plot(np.arange(sequence_length), candle_data[:, 0], 'k-', linewidth=2)

    # Highlight zigzag patterns
    if labels[i] == 1:
        ax.axvline(x=sequence_length - 1, color='b', linestyle='--')

    ax.set_xlim(0, sequence_length - 1)
    ax.set_ylim(min(candle_data[:, 2]) - 0.1, max(candle_data[:, 1]) + 0.1)
    ax.set_yticks([])
    ax.set_xticks([])


IndexError: invalid index to scalar variable.

In [ ]:

plt.tight_layout()
plt.show()
